version: '3'
services:
    backend:
        build:
            context: '.'
            dockerfile: './docker/backend.dockerfile'
        volumes:
            - './config:/app/config:ro'
            - './tmp:/app/tmp'
            - './logs:/app/logs'
            - '~/.aws/credentials:/root/.aws/credentials:ro'
        ports: 
            - '9001:80'

    queue_processor:
        build:
            context: '.'
            dockerfile: './docker/queueProcessor.dockerfile'
        volumes:
            - './config:/app/config:ro'
            - './tmp:/app/tmp'
            - './logs:/app/logs'
            - '~/.aws/credentials:/root/.aws/credentials:ro'


