version: '3'
services:
    app:
        build:
            context: '.'
            dockerfile: './docker/app.dockerfile'
        volumes:
            - './config:/deploy/config:ro'
            - './tmp:/deploy/tmp'
            - './logs:/deploy/logs'
            - '~/.aws/credentials:/root/.aws/credentials:ro'
        ports: 
            - '9001:80'

    queue_processor:
        build:
            context: '.'
            dockerfile: './docker/app.dockerfile'
        volumes:
            - './config:/deploy/config:ro'
            - './tmp:/deploy/tmp'
            - './logs:/deploy/logs'
            - '~/.aws/credentials:/root/.aws/credentials:ro'
        command: python3 jpsurvProcessor.py

