version: '3'
services:
    app:
        build:
            context: '.'
            dockerfile: './docker/app.dockerfile'
        volumes:
            - './config:/deploy/config:ro'
            - './tmp:/deploy/tmp'
            - './logs:/deploy/logs'
            - '~/.aws:/root/.aws:ro'
        ports: 
            - '9001:80'

    analysis_queue_processor:
        build:
            context: '.'
            dockerfile: './docker/app.dockerfile'
        volumes:
            - './config:/deploy/config:ro'
            - './tmp:/deploy/tmp'
            - './logs:/deploy/logs'
            - '~/.aws:/root/.aws:ro'
        command: python3 jpsurvProcessor.py

    download_queue_processor:
        build:
            context: '.'
            dockerfile: './docker/downloadQueue.dockerfile'
        volumes:
            - './config:/deploy/config:ro'
            - './tmp:/deploy/tmp'
            - './logs:/deploy/logs'
            - '~/.aws:/root/.aws:ro'


