version: '3'
services:
    backend:
        build:
            context: '.'
            dockerfile: './docker/backend.dockerfile'
        volumes:
            - './config:/deploy/config:ro'
            - './tmp:/deploy/tmp'
            - './logs:/deploy/logs'
            - '~/.aws:/root/.aws:ro'
        ports: 
            - '9001:80'

    queue_processor:
        build:
            context: '.'
            dockerfile: './docker/queueProcessor.dockerfile'
        volumes:
            - './config:/deploy/config:ro'
            - './tmp:/deploy/tmp'
            - './logs:/deploy/logs'
            - '~/.aws:/root/.aws:ro'


